# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: beeec3162221d38cddcbf03a71bbda21a94861e5789116fa3fc0bc341850faa0aa2a8f19b9642e3ea6afd7827609facdc70815699c401e0fe3c4f988023d2c38

test:
  secret_key_base: bd9e9f96bbbed3966ccf3328f868c5d0a03e86701e36716ef4a0efbdb8fd0ad1e71663642398b2278020d035936d072ac92e5de389e3211f9225f74d06c09a4e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
